### ISSUE TITLE
New page for "directory" of taxonomy terms

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-photo-directory#10]
> There are three pages that are currently on the site that list the items in each taxonomy, kind of like a directory.
>
> - [Categories](https://wordpress.org/photos/c/)
> - [Orientations](https://wordpress.org/photos/orientation/)
> - [Colors](https://wordpress.org/photos/color/)
>
> It might also be possible to redirect these 3 urls to a single new page with all 3 lists

_Originally posted by @ryelle in https://github.com/ryelle/wporg-photo-directory/discussions/1#discussioncomment-10963255_

Page name TBD, but here's a mockup:

![directory](https://github.com/user-attachments/assets/bf0440bd-cb21-4a99-a022-6851cdbccdfd)

[Figma](https://www.figma.com/design/j5lxNGoGKlzhSfhYNFQAxZ/Photos-Directory?node-id=3807-7214&m=dev)

**Comment by ndiego** [comment]
What about "Filters"?

**Comment by fcoveram** [comment]
I'm not convinced, but I can't think of any other term that gathers taxonomies.

**Comment by ndiego** [comment]
> I'm not convinced, but I can't think of any other term that gathers taxonomies.

Same 😅

**Comment by ryelle** [comment]
Added this page. This uses the default term list block, so we're slightly limited in the formatting (that's why the count is not part of the link text).

Also added an issue about making the terms more human-friendly #20

![Image](https://github.com/user-attachments/assets/2d51cea0-865d-4bd1-9ece-27773a77d865)

**Comment by ryelle** [comment]
The page exists on the live site now (nothing's there unless you're previewing the new theme) — https://wordpress.org/photos/filters/?new-theme=1
