### ISSUE TITLE
Single photo: Add links to explore more photos

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-photo-directory#15]
> Here is another idea. Instead of placing the link in either inside the local nav or in the search results page, we could add it next to a link to the metadata index page in the photo details one. Here is a mockup.
>
> ![Mockup of photo details page](https://github.com/user-attachments/assets/8c3a2424-0861-4c17-b325-fab3225488ff)

_Originally posted by @fcoveram in https://github.com/WordPress/wporg-photo-directory/discussions/1#discussioncomment-11114617_

This would add that last section to the page:

> _Discover more_ content submitted by the WordPress community
> [See the metadata index] [Take me to a random photo]

(See #10 for naming the "metadata index")

**Comment by ndiego** [comment]
If "Filters" works for https://github.com/WordPress/wporg-photo-directory/issues/10, then perhaps:

> _Discover more_ content submitted by the WordPress community
> [Browse photos by filter] [Take me to a random photo]

**Comment by ryelle** [comment]
I forgot the exact wording here and went with "Browse the filters" for the empty state of "My favorites", but I think I like that better — "Browse photos by filter" sounds like it would take you back to a grid view of photos. Any thoughts about that variation?

![Image](https://github.com/user-attachments/assets/630f3a18-6c43-4854-8c55-7e39de7d0bd6)

**Comment by fcoveram** [comment]
+1 to "Browse photos by filter"

**Comment by ryelle** [comment]
You don't think that sounds like you'll land on a photos grid?

**Comment by fcoveram** [comment]
Not really, especially when it's next to "Explore all photos," but I don't have a strong preference. It might be my non-native interpretation.

**Comment by ndiego** [comment]
I don't have a strong opinion either. Let's go with what you have implemented @ryelle.
