### ISSUE TITLE
Categories, colors, and orientation names are not human-friendly

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-photo-directory#20]
The terms on the site all use slug-ified names for the term name, e.g., `arts-culture`, `food-drink`, or even just the lowercase `black`. It's more human-friendly if those use proper spaces and capitalization, to match the rest of the wporg network sites.

For example…
- arts-culture -> Arts & culture
- food-drink -> Food & drink
- black -> Black

And so on. The slugs would stay the same, as would the term IDs, so this should not affect assignment to existing photos. The change can be made directly on the site for the 13 categories, 13 colors, and 3 orientations.

![Image](https://github.com/user-attachments/assets/7b756a18-779e-4009-a85d-aedffc695873)

Before just making these changes I want to check in whether anything is tied to term name. What do you think @coffee2code?

**Comment by coffee2code** [comment]
Using human-readable names for the category, color, and orientation taxonomy terms would be best and has a 👍🏽 from me. I don't foresee an issue making the change within WP.

I can follow-up with adjusting `Photo::TAGS_TO_CATEGORY` to define human-readable names for each category. That is used by `CLI::init()`, which I can also update to capitalize the colors and orientations when a new site is created. This obviously doesn't affect the .org site so it's of the lowest priority.

**Comment by ryelle** [comment]
I've updated this on the live site, the terms are now capitalized on both the current theme and the new theme preview.

<img width="300" src="https://github.com/user-attachments/assets/b10811f6-20dd-4c4c-bef6-393f7be648f1" />

<img width="300" src="https://github.com/user-attachments/assets/420732bc-bfaa-4e19-87b2-f0d52f302f66" />
