### ISSUE TITLE
Default OpenGraph image for homepage/fallbacks

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-photo-directory#23]
Like https://github.com/WordPress/wporg-theme-directory/issues/117, this site also needs a default opengraph image for embeds.

**Comment by fcoveram** [comment]
Here is the image.

![WordPress Photo Directory OpenGraph image](https://github.com/user-attachments/assets/acf0d242-02cc-4d61-b843-1bc26c7b9e33)

Thanks
