### ISSUE TITLE
Place photo filters in columns

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-photo-directory#25]
The filters stacked in a single column make it a bit hard to see what's available. I wonder if we could place them in columns. I realize this might not scale in the future if more filters are added, but I think this would look better in the meantime. 

| Current | Proposed |
|-|-|
|![Image](https://github.com/user-attachments/assets/dde34c9a-9bda-429d-830a-725fae8d1783)|![Image](https://github.com/user-attachments/assets/7582ab28-5e9d-4072-8a0e-a5fce0564cef)|

**Comment by fcoveram** [comment]
You're right about scaling it, but I agree it works for now. Another version could be listing every link in rows from left to right, just like the "Site tags" section in [this](https://wordpress.org/showcase/the-line-hotels/) site details page in Showcase.

**Comment by ndiego** [comment]
> You're right about scaling it, but I agree it works for now. Another version could be listing every link in rows from left to right, just like the "Site tags" section in [this](https://wordpress.org/showcase/the-line-hotels/) site details page in Showcase.

Oh yeah, that could work too. I have no strong preference. This is what it would look like: 

![Image](https://github.com/user-attachments/assets/97e07e25-4794-4d8c-a732-15d2e796ea84)

I applied the following CSS to the `<ul>` element:

```css
display: flex;
flex-wrap: wrap;
gap: 0 14px;
```

**Comment by fcoveram** [comment]
It can scale, but it makes the content harder to scan due to the zig-zag spacing between items. I'm fine going with the three columns.

**Comment by ryelle** [comment]
@fcoveram In the figma file, the Filters page design is the wide width, 1160px, but the content itself is still within the default width (680px). The other pages ([Guidelines](https://wordpress.org/photos/guidelines/?new-theme=1), [Submit](https://wordpress.org/photos/submit/?new-theme=1), etc) are 680px. Is this page intentionally different?

For example, here's the guidelines page, and then the two width options. Note that at this browser-width, the local nav lines up with the page title, but at larger widths this will be centered, like the default width is.

![Image](https://github.com/user-attachments/assets/6e3da24d-7928-40d1-bf6d-62c47f0b8a71)

| Wide (1160) | Default (680) |
|---|---|
| ![Image](https://github.com/user-attachments/assets/7c8ede97-9cb3-4f06-a12b-e14901cc9d46) | ![Image](https://github.com/user-attachments/assets/22d7a960-8c54-4b6d-9438-3f305683dec4) |

**Comment by ndiego** [comment]
I think the Filters page should be the default width, but defer to @fcoveram for the final call.

**Comment by fcoveram** [comment]
The initial stack version was based on 1160, like [this index page](https://wordpress.org/documentation/technical-guides/) in Documentation. But I'm fine changing to default.

![Image](https://github.com/user-attachments/assets/52f23f87-f142-4964-bdbe-56d95ec1f484)

**Comment by ryelle** [comment]
I went with default, for consistency with the other pages on the site.
