### ISSUE TITLE
Horizontal overflow in archive pages

### ISSUE THREAD

**Issue by ironnysh** [WordPress/wporg-photo-directory#26]
**Describe the bug**
The new design causes a horizontal overflow on mobile. Seems like the element that’s responsible is the filters navigation bar (`wporg-query-filters`).

**To Reproduce**
1. Go to 
https://wordpress.org/photos/?new-theme=1
2. See error

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 18
 - Browser: Safari

**Screenshots**
![Image](https://github.com/user-attachments/assets/c50b533d-8066-44a9-977e-13e00f51150c)

**Comment by ironnysh** [comment]
Hi @ryelle, thanks for the quick fix!
The issue is still happening, though. Maybe it hasn't been deployed yet?

**Comment by ryelle** [comment]
Thanks for the report! It was fixed, but the old CSS is likely cached for you. You can clear your cache, or wait a little longer for another change that should fix the sticky caching.

**Comment by ironnysh** [comment]
> You can clear your cache

Magic :-) Thanks again!
