### ISSUE TITLE
Public and private section divider in local nav

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#27]
**Describe the bug**
The local nav separates the public and private section through a dot divider, but in current local nav is not visible.

Learn section has it correctly. It's placed before "My courses" and "Log in" links.

![Learn's local nav](https://github.com/user-attachments/assets/15ee380e-73ec-427f-a089-8159c2601d1a)

**Expected behavior**
When logged out, the dot divider should be visible before the "Log in" link.

**Screenshots**
![Screenshot of Photos' local nav](https://github.com/user-attachments/assets/d09c037f-7c2d-45c5-a7a1-080070e418e4)

**Comment by ryelle** [comment]
Done in a36f7aab091d8789c01e0df4d46a3c7545f4874a
