### ISSUE TITLE
Show "My photos" link in local nav

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#28]
Related to #27 

As recently implemented in other sections, the "My photos" link in local nav should be visible for both logged out and logged in users.

| Implementation | Design |
|:---|:---|
| ![Image](https://github.com/user-attachments/assets/f66d1121-4e7a-4814-b4ec-5c7cdae9ca98) | ![Image](https://github.com/user-attachments/assets/deadefc1-2a11-4ac2-97cb-6a5d5112b426) |

Regarding the content displayed in "My photos" page for logged out users, I'd like your thoughts on what's doable. If I understand correctly, we're reusing the layout when users are logged in, but then I noticed that in Learn, the "My courses" takes you to the log in process.

**Comment by ryelle** [comment]
@fcoveram @ndiego On the call we decided this was okay to omit, right? So the "My photos" link will only appear when logged in.

**Comment by fcoveram** [comment]
Yes. Show "My photos" when logged in.

**Comment by ryelle** [comment]
Okay, swapping out My photos & My favorites will happen with #32, no separate action needed from this issue.
