### ISSUE TITLE
Replace "My favorites" label with "My photos"

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#32]
As per [this suggestion](https://github.com/WordPress/wporg-photo-directory/discussions/1#discussioncomment-11055785), use "My photos" instead of "My favorites" to avoid confusion between user profiles.

![Screenshot of My favorites page in Photos section](https://github.com/user-attachments/assets/12d6fa28-a37a-4373-babf-71da3d5bf6e2)

**Comment by ryelle** [comment]
I'm pretty sure that suggestion was to not use "my profile", not that it should always be "My photos". Also, favorites and an author's archive are different things (using a similar layout). Do you not want to link directly to favorites anymore?

**Comment by ryelle** [comment]
This should be swapped out with "My photos", which will link to the current user's author archive. We'll also swap the tabs so that "Contributed" is first.

![Image](https://github.com/user-attachments/assets/eaa13a99-526e-4241-8590-0a867bad8747)

**Comment by fcoveram** [comment]
I just noticed that "Contributed" label is "Contributions" in the designs. What do you think of the latter? Contributions and Favorites are nouns while contributed is a verb.

**Comment by ryelle** [comment]
In speaking we've been calling it "contributed" so I used that, probably didn't notice it was different in the design. I'll change to to "contributions".
