### ISSUE TITLE
Apply blueberry 2 to links above footer

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-photo-directory#34]
**Describe the solution you'd like**
To links in the section above footer, we could apply `blueberry-2` to make them consistent with other sections like in Documentation, Forums, and Developer Resources.

Here is a mockup of how it would look like.

![Image](https://github.com/user-attachments/assets/b1f3147c-addc-432d-8513-3bf548da024d)

**Comment by ndiego** [comment]
Good catch. I agree.

**Comment by ryelle** [comment]
I'll update this, but I've also commented on https://github.com/WordPress/wporg-parent-2021/issues/148 suggesting we switch to blueberry-3 for links on the charcoals.
