### ISSUE TITLE
Change CC0 Link?

### ISSUE THREAD

**Issue by macmanx2** [WordPress/wporg-photo-directory#38]
**Is your feature request related to a problem? Please describe.**
I've noticed that the CC0 link, at individual images, on the Guidelines, on the License page, and probably other spots I might have missed goes to https://creativecommons.org/public-domain/cc0/

This page reads more like an introduction to the CC0 license than an actual license summary. It almost reads like a press release, to be honest.

It's not bad, but I think there's a better option.

**Describe the solution you'd like**
I propose that the CC0 links go to https://creativecommons.org/publicdomain/zero/1.0/ instead, which is the actual summary of the license and still includes links to the full legal text and more info.

When you go through the license chooser at https://chooser-beta.creativecommons.org this is also the link you're given when CC0 applies.

Overall, I think, at the very least for the License and individual photo pages, it's a better option that what's linked to now.

**Comment by ryelle** [comment]
@macmanx2 Is this just a suggestion for discussion, or should this change be made now? If the former, who should make the call to update the link?

**Comment by ndiego** [comment]
> I propose that the CC0 links go to https://creativecommons.org/publicdomain/zero/1.0/ instead, which is the actual summary of the license and still includes links to the full legal text and more info.

After researching this, I agree that https://creativecommons.org/publicdomain/zero/1.0/ seems like a better place to direct users.

**Comment by macmanx2** [comment]
@ryelle Personally I think the change should be made now, but ... IDK who should make the call. 😅

**Comment by coffee2code** [comment]
This is reasonable. I've made the changes to the plugin and old theme.

**Comment by macmanx2** [comment]
Thank you!

**Comment by ryelle** [comment]
> Personally I think the change should be made now, but ... IDK who should make the call. 😅

Fair, some teams have more structure/approval processes that others so just playing it safe 🙂 

I'll update this in the new theme before launch.

**Comment by fcoveram** [comment]
Agree with changing to https://creativecommons.org/publicdomain/zero/1.0/ As former designer at Creative Commons, the Deed version was made to be more content-friendly.

**Comment by ryelle** [comment]
I've made the change in the theme, and on the License & Guidelines pages. All the links should now go to `https://creativecommons.org/publicdomain/zero/1.0/`.
