### ISSUE TITLE
Single photo page

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-photo-directory#4]
![Individual photo](https://github.com/user-attachments/assets/7b520d7d-bfa7-4bfe-b5e2-ccc5c5d4e5c2)

[Figma link](https://www.figma.com/design/j5lxNGoGKlzhSfhYNFQAxZ/Photos-Directory?node-id=3777-6271&m=dev)

- [x] #5
- [x] #6
- [x] Style the featured image
- [x] Display the alt text
- [x] #7 (Image info & EXIF data)
- [x] #8
- [x] License/usage (same text across all photos)

**Comment by ryelle** [comment]
@fcoveram What is the logic for the featured image + grey background? Initially, I had set it up so that the grey box is a square, so it's the same height across all photos and has that top or side spacing like in the mockup. But I realized that the grey in the mockup is not square, so I've also tried 16:9, but then this doesn't have the top spacing (it would need a photo with an aspect ratio more extreme than 16:9).

Examples:

| | Landscape | Portrait | Square |
|---|---|---|---|
| Square | ![Image](https://github.com/user-attachments/assets/a9f90694-d0b0-4078-94a9-74eb92df8726) | ![Image](https://github.com/user-attachments/assets/9f6dd314-ae8e-4219-97eb-646d385a0cb9) | ![Image](https://github.com/user-attachments/assets/3a925d50-4f4a-47b7-aa33-ccf80d084f2b) |
| 16:9 | ![Image](https://github.com/user-attachments/assets/a56679ec-49d1-4ea6-9819-665021b2fe06) | ![Image](https://github.com/user-attachments/assets/9fc3847f-db13-4868-a79a-3999cec7dc8a) | ![Image](https://github.com/user-attachments/assets/fc0a96a7-b9ad-4aad-b4ec-39121d125396) |

This should have the same container aspect ratio on large and small screens, which is also not currently the case in the mockup.

**Comment by fcoveram** [comment]
My mistake. I thought the mockups were 16:9. The desktop version is close to the ratio but not fully accurate.

The idea was having a 16:9 in both desktop and mobile. So the 16:9 tests in the table above are the expected outcome.

I was looking the mockups again and I'm not sure about the gray as background color to outline the image container. What do you think of it? The outcome on dev feels different than a mockup so curious about your thoughts.

**Comment by ryelle** [comment]
> The idea was having a 16:9 in both desktop and mobile. So the 16:9 tests in the table above are the expected outcome.

great 👍🏻 

> I was looking the mockups again and I'm not sure about the gray as background color to outline the image container. What do you think of it? The outcome on dev feels different than a mockup so curious about your thoughts.

I like the grey, but it's fairly easy to change the style of that container if you wanted. Maybe wait for the theme preview to be live so you can see it for real?

**Comment by fcoveram** [comment]
>  Maybe wait for the theme preview to be live so you can see it for real?

Great. My main concern is users understand the grey area as part of the image.
