### ISSUE TITLE
Add related images section to single photo page.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-photo-directory#42]
**Is your feature request related to a problem? Please describe.**
As we do in the the WordPress showcase, we should show related images at the bottom of a single photo page. They don't have to be related if that's a bigger technical challenge. A random list to help users continue their browsing would work too.

## WordPress.org Showcase

<img width="1322" alt="Image" src="https://github.com/user-attachments/assets/fa2f18a0-483f-4819-b4ff-ba2299210bd8" />

**Comment by ryelle** [comment]
This wasn't part of the old site, or part of the redesign mockups. The links (like the category, color, etc) and the "Discover more content …" sections are meant to be the way for users to get to other photos. I don't think a random list would be any more helpful than the links.

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/08e7be61-acaa-4852-afd2-b0e8159a1c6f" />

<img width="871" alt="Image" src="https://github.com/user-attachments/assets/a6bc0569-d808-41ae-8134-61ec3870c7cf" />

If you still this this would be useful, could you open a discussion to propose this? This way we can keep issues to tasks-to-do.
