### ISSUE TITLE
Single page and submission form

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-photo-directory#9]
The pages (like `https://wordpress.org/photos/license/`, `https://wordpress.org/photos/guidelines/`) are simply editor pages, with page title & page content blocks. These should inherit the default styles, and not require much customization.

The submission form is page content swapped out based on the page slug. The form will need CSS styling to match the redesign.

![Submit](https://github.com/user-attachments/assets/102dc5ba-daa0-4a98-a612-08c4047356c8)

Error states might need help — these seem to be added via JS on submission.

<img width="975" alt="Screenshot 2024-10-18 at 5 55 16 PM" src="https://github.com/user-attachments/assets/67c9320f-ba71-43f3-8e42-0629c1f144c7">

**Comment by coffee2code** [comment]
The submit page also potentially has other content injected into it by the plugin: a section that has a table listing the current user's submissions awaiting moderation, and a section listing their recent submissions. I've added a screenshot and explanation of these elements in [a comment](https://github.com/WordPress/wporg-photo-directory/discussions/1#discussioncomment-11105406) to the design discussion thread.

**Comment by fcoveram** [comment]
There is a thread in #1 related to photos waiting for moderation that impacts this page. I wasn't sure whether to share [my comment](https://github.com/WordPress/wporg-photo-directory/discussions/1#discussioncomment-11334241) here or there, yet putting my thought here.

> Thanks for the context.
> 
> Regarding the info displayed in the table, we could continue without showing the thumbnail and just update the style of the current table (the one shown in [this screenshot](https://private-user-images.githubusercontent.com/515778/381750022-557fa102-3328-48a6-bfc5-efaa0f5fbce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODExNjUsIm5iZiI6MTczMjE4MDg2NSwicGF0aCI6Ii81MTU3NzgvMzgxNzUwMDIyLTU1N2ZhMTAyLTMzMjgtNDhhNi1iZmM1LWVmYWEwZjVmYmNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwOTIxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTk1ZjRmZGU0MjhkY2NjOTc1ZDMyZDExOTcxYTNiODg0MzFkOGUzNmRmY2Y3NDY4MTg2MWIyNmE5NjEwZmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Akdrnt4rwMk8Un9a18D28SMhyELRctmIeYvV1P49q1I)) with the latest changes. I couldn't find an example in the current site, but I'm thinking of a zebra-striping with gray border. Please correct me @ryelle if I'm wrong.
> 
> For the submission extension, I lean on adding more rows to the same table and not hiding anything behind a "see more" action. Perhaps, and since the page goal is about submitting photos, the form could be swapped with the awaiting moderation section to have the latter at the end of the page.

**Comment by ryelle** [comment]
Let's keep discussion over there, I actually need to close this issue since I already implemented it 😣 

Any change to the pending submission table, once decided, can be a new issue.
